export const INGREDIENT_CREATE_REQUEST = "INGREDIENT_CREATE_REQUEST";
export const INGREDIENT_CREATE_SUCCESS = "INGREDIENT_CREATE_SUCCESS";
export const INGREDIENT_CREATE_FAIL = "INGREDIENT_CREATE_FAIL";

export const INGREDIENT_REQUEST = "INGREDIENT_REQUEST";
export const INGREDIENT_SUCCESS = "INGREDIENT_SUCCESS";
export const INGREDIENT_FAIL = "INGREDIENT_FAIL";

export const INGREDIENT_UPDATE_REQUEST = "INGREDIENT_UPDATE_REQUEST";
export const INGREDIENT_UPDATE_SUCCESS = "INGREDIENT_UPDATE_SUCCESS";
export const INGREDIENT_UPDATE_FAIL = "INGREDIENT_UPDATE_FAIL";

export const INGREDIENT_DELETE_REQUEST = "INGREDIENT_DELETE_REQUEST";
export const INGREDIENT_DELETE_SUCCESS = "INGREDIENT_DELETE_SUCCESS";
export const INGREDIENT_DELETE_FAIL = "INGREDIENT_DELETE_FAIL";
