export const MEAL_REQUEST = "MEAL_REQUEST";
export const MEAL_SUCCESS = "MEAL_SUCCESS";
export const MEAL_FAIL = "MEAL_FAIL";

export const MEAL_DETAILS_REQUEST = "MEAL_DETAILS_REQUEST";
export const MEAL_DETAILS_SUCCESS = "MEAL_DETAILS_SUCCESS";
export const MEAL_DETAILS_FAIL = "MEAL_DETAILS_FAIL";
