
//cashier

export const ORDER_CASHIER_CREATE_REQUEST = "ORDER_CASHIER_CREATE_REQUEST";
export const ORDER_CASHIER_CREATE_SUCCESS = "ORDER_CASHIER_CREATE_SUCCESS";
export const ORDER_CASHIER_CREATE_FAIL = "ORDER_CASHIER_CREATE_FAIL";
export const ORDER_CASHIER_CREATE_RESET = "ORDER_CASHIER_CREATE_RESET";

export const ORDER_CASHIER_LIST_REQUEST = "ORDER_CASHIER_LIST_REQUEST";
export const ORDER_CASHIER_LIST_SUCCESS = "ORDER_CASHIER_LIST_SUCCESS";
export const ORDER_CASHIER_LIST_FAIL = "ORDER_CASHIER_LIST_FAIL";

export const ORDER_CASHIER_DETAILS_REQUEST = "ORDER_CASHIER_DETAILS_REQUEST";
export const ORDER_CASHIER_DETAILS_SUCCESS = "ORDER_CASHIER_DETAILS_SUCCESS";
export const ORDER_CASHIER_DETAILS_FAIL = "ORDER_CASHIER_DETAILS_FAIL";
export const ORDER_CASHIER_DETAILS_RESET = "ORDER_CASHIER_DETAILS_RESET";
