export const rows = [
  {
    id: 12345,
    date: "27 April 2021, 12:42 AM",
    customer: "Johny Bravo",
    location: "Philippines",
    amount: 500,
    status: "Pending",
    action: "...",
  },
  {
    id: 34534,
    date: "12 May 2021, 12:42 AM",
    customer: "Juan Delacruz",
    location: "Philippines",
    amount: 500,
    status: "Delivered",
    action: "...",
  },
  {
    id: 29687,
    date: "14 March 2021, 12:42 AM",
    customer: "Pedro Penduko",
    location: "Philippines",
    amount: 500,
    status: "Pending",
    action: "...",
  },
  {
    id: 34443,
    date: "28 March 2021, 12:42 AM",
    customer: "Taylor Swift",
    location: "Philippines",
    amount: 500,
    status: "Delivered",
    action: "...",
  },
  {
    id: 33344,
    date: "1 March 2021, 12:42 AM",
    customer: "Shawn Mendes",
    location: "Philippines",
    amount: 500,
    status: "Delivered",
    action: "...",
  },
  {
    id: 22111,
    date: "1 March 2021, 12:42 AM",
    customer: "Ed sheeran",
    location: "Philippines",
    amount: 500,
    status: "Pending",
    action: "...",
  },
  {
    id: 11115,
    date: "1 March 2021, 12:42 AM",
    customer: "John Doe",
    location: "Philippines",
    amount: 500,
    status: "Delivered",
    action: "...",
  },
];

export const headCells = [
  "Order ID",
  "Date",
  "Customer",
  "Location",
  "Amount",
  "Order Status",
  "Action",
];
